#!/bin/sh
#
# MarkLogic Server (Re)-Installation script for debian 
# To start with your own MarkLogic Scripts I would advise you to check out
# $ cat /etc/init.d/MarkLogic 
#
# Based on the work of Dave Cassel that is available at:
#  http://blog.davidcassel.net/2009/12/upgrading-marklogic-server-on-ubuntu/
# 
# Copyright (c) 2010 Nuno Job [about.nunojob.com]. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# The use of the Apache License does not indicate that this project is
# affiliated with the Apache Software Foundation.
usage="Usage: $0 filename"

if [ "$#" -ne 1 ]; then
 echo "Error: Wrong number of arguments"
 echo $usage
 return
fi

echo "Installing MarkLogic Server on Debian based Linux distributions"
echo "  . Installing dependancies"
DEBIAN_FRONTEND=sudo noninteractive apt-get install -q -y rpm alien wajig > /dev/null 2>&1
echo "  . Purging previous versions of MarkLogic Server"
sudo dpkg --purge marklogic > /dev/null 2>&1
sudo rm -rf /opt/MarkLogic/ > /dev/null 2>&1
# uncomment this if you want to delete databases and apps
#sudo rm -rf /var/opt/MarkLogic/ > /dev/null 2>&1
echo "  . Convert rpm to deb"
sudo alien --to-deb --verbose -k $1 > /dev/null 2>&1
deb=`ls | grep marklogic_*.deb`
echo "  . Installing deb"
sudo dpkg -i $deb > /dev/null 2>&1
echo "  . Ensuring necessary directories exist"
sudo mkdir /var/lock/subsys > /dev/null 2>&1
echo "  . Creating the marklogic command"
sudo touch /usr/local/bin/marklogic
echo '#!/bin/sh
sudo /etc/init.d/MarkLogic $*' | sudo tee /usr/local/bin/marklogic > /dev/null 2>&1
sudo chmod 755 /usr/local/bin/marklogic > /dev/null 2>&1
echo "  . Installing this script in /bin. $usage"
sudo touch /usr/local/bin/$0
cat $0  | sudo tee /usr/local/bin/$0 > /dev/null 2>&1
sudo chmod 755 /usr/local/bin/$0 > /dev/null 2>&1
echo "  . Starting MarkLogic"
marklogic start > /dev/null 2>&1
echo "Installation Complete!"
