#!/bin/bash
#
# MarkLogic Server (Re)-Installation script for debian 
# To start with your own MarkLogic Scripts I would advise you to check out
# $ cat /etc/init.d/MarkLogic 
#
# Based on the work of Dave Cassel that is available at:
#  http://blog.davidcassel.net/2009/12/upgrading-marklogic-server-on-ubuntu/
# 
# Copyright (c) 2010 Nuno Job [about.nunojob.com]. All Rights Reserved.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 
# The use of the Apache License does not indicate that this project is
# affiliated with the Apache Software Foundation.
usage="Usage: $0 [OPTION]... FILE

Options:
  -D Turns debug on"

function debug_echo () {
  if [ ! -z "$debug" ]; then
    for line in "$@"
      do
	      echo "$(date) - [MarkLogic] $line"
      done
  fi }

function debug_exec () {
  if [ ! -z "$debug" ]; then
    debug_echo "$1"
    inst=&$1
  else
    inst=&$1 > /dev/null 2>&1
  fi }

debug=""

while getopts "D" opts
do case "$opts" in
  D) debug="1";;
  h) echo >&2 "$usage"
     exit 1;;
  ?) echo >&2 "$usage"
     exit 1;;
   esac
done

shift $(($OPTIND - 1))

if [ "$#" -ne 1 ]; then
 echo "Error: Wrong number of arguments"
 echo $usage
 return 2
fi

echo "Installing MarkLogic Server on Debian based Linux distributions"
echo "  . Installing dependancies"
DEBIAN_FRONTEND=sudo noninteractive apt-get install -q -y rpm alien wajig > /dev/null 2>&1
echo "  . Purging previous versions of MarkLogic Server"
debug_exec "sudo dpkg --purge marklogic"
debug_exec "sudo rm -rf /opt/MarkLogic"
# uncomment this if you want to delete databases and apps
#debug_exec "sudo rm -rf /var/opt/MarkLogic"
echo "  . Convert rpm to deb"
debug_exec "sudo alien --to-deb --verbose -k ./$1"
deb=`ls | grep marklogic_*.deb`
echo "  . Installing deb"
debug_exec "sudo dpkg -i $deb"
echo "  . Ensuring necessary directories exist"
debug_exec "sudo mkdir /var/lock/subsys"
echo "  . Creating the marklogic command"
debug_exec "sudo touch /usr/local/bin/marklogic"
debug_exec "echo '#!/bin/sh
sudo /etc/init.d/MarkLogic $*' | sudo tee /usr/local/bin/marklogic"
debug_exec "sudo chmod 755 /usr/local/bin/marklogic"
echo "  . Starting MarkLogic"
debug_exec "marklogic start"
echo "Installation Complete!"
